name: Production Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_WORKSPACE: production

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:

      #######################################################
      # Checkout Repository
      #######################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      #######################################################
      # Configure AWS Credentials
      #######################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #######################################################
      # Setup Terraform
      #######################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #######################################################
      # Terraform Init
      #######################################################

      - name: Terraform Init
        run: terraform init


      #######################################################
      # Terraform Format Check
      #######################################################

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      #######################################################
      # Terraform Validate
      #######################################################

      - name: Terraform Validate
        run: terraform validate

      #######################################################
      # Setup TFLint
      #######################################################

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      #######################################################
      # Run TFLint
      #######################################################

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      #######################################################
      # Read Terraform Outputs
      #######################################################

      - name: Read Terraform Outputs
        id: tf
        run: |
          echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
          echo "service_name=$(terraform output -raw service_name)" >> $GITHUB_OUTPUT
          echo "task_family=$(terraform output -raw task_definition_family)" >> $GITHUB_OUTPUT
          echo "container_name=$(terraform output -raw container_name)" >> $GITHUB_OUTPUT
          echo "repository_url=$(terraform output -raw repository_url)" >> $GITHUB_OUTPUT

      #######################################################
      # Login to Amazon ECR
      #######################################################

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      #######################################################
      # Generate Image Tag
      #######################################################

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      #######################################################
      # Build Docker Image
      #######################################################

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ steps.tf.outputs.repository_url }}:${IMAGE_TAG} \
          -t ${{ steps.tf.outputs.repository_url }}:latest \
          ../app

      #######################################################
      # Push Docker Images
      #######################################################

      - name: Push Docker Images
        run: |
          docker push ${{ steps.tf.outputs.repository_url }}:${IMAGE_TAG}
          docker push ${{ steps.tf.outputs.repository_url }}:latest

      #######################################################
      # Download Current Task Definition
      #######################################################

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ steps.tf.outputs.task_family }} \
            --query taskDefinition \
            > task-definition.json

      #######################################################
      # Render Updated Task Definition
      #######################################################

      - name: Render Task Definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: terraform/task-definition.json
          container-name: ${{ steps.tf.outputs.container_name }}
          image: ${{ steps.tf.outputs.repository_url }}:${{ env.IMAGE_TAG }}

      #######################################################
      # Save Current Task Definition
      #######################################################

      - name: Save Current Task Definition
        id: current
        run: |
          CURRENT_TASK=$(aws ecs describe-services \
            --cluster ${{ steps.tf.outputs.cluster_name }} \
            --services ${{ steps.tf.outputs.service_name }} \
            --query "services[0].taskDefinition" \
            --output text)

          echo "CURRENT_TASK=$CURRENT_TASK"

          echo "task_definition=$CURRENT_TASK" >> $GITHUB_OUTPUT

      #######################################################
      # Deploy to ECS
      #######################################################

      - name: Deploy to ECS
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: ${{ steps.tf.outputs.service_name }}
          cluster: ${{ steps.tf.outputs.cluster_name }}
          wait-for-service-stability: false

      #######################################################
      # Wait for ECS Deployment
      #######################################################

      - name: Wait for ECS Service
        id: wait
        continue-on-error: true
        run: |
          aws ecs wait services-stable \
            --cluster ${{ steps.tf.outputs.cluster_name }} \
            --services ${{ steps.tf.outputs.service_name }} \
            --region $AWS_REGION

      #######################################################
      # Verify ALB Health
      #######################################################

      - name: Verify Deployment
        id: verify
        continue-on-error: true
        run: |

          TARGET_GROUP=$(aws elbv2 describe-target-groups \
            --names ecommerce-production-tg \
            --query "TargetGroups[0].TargetGroupArn" \
            --output text)

          echo "Waiting 30 seconds..."
          sleep 30

          HEALTH=$(aws elbv2 describe-target-health \
            --target-group-arn $TARGET_GROUP \
            --query "TargetHealthDescriptions[*].TargetHealth.State" \
            --output text)

          echo "Health = $HEALTH"

          echo "$HEALTH" | grep unhealthy && exit 1
          echo "$HEALTH" | grep initial && exit 1


      #######################################################
      # Rollback if Health Check Failed
      #######################################################

      - name: Rollback
        if: steps.wait.outcome == 'failure' || steps.verify.outcome == 'failure'
        run: |

          echo "Deployment failed."

          echo "Rolling back to:"
          echo "${{ steps.current.outputs.task_definition }}"

          aws ecs update-service \
            --cluster ${{ steps.tf.outputs.cluster_name }} \
            --service ${{ steps.tf.outputs.service_name }} \
            --task-definition "${{ steps.current.outputs.task_definition }}" \
            --force-new-deployment

          aws ecs wait services-stable \
            --cluster ${{ steps.tf.outputs.cluster_name }} \
            --services ${{ steps.tf.outputs.service_name }}

          echo "Rollback completed."

          aws ecs describe-services \
            --cluster ${{ steps.tf.outputs.cluster_name }} \
            --services ${{ steps.tf.outputs.service_name }} \
            --query "services[0].taskDefinition"

          echo "Deployment failed. Service has been rolled back to the previous stable task definition."

          exit 1


      #######################################################
      # Summary
      #######################################################

      - name: Deployment Summary
        if: success()
        run: |
          echo "Production Deployment Successful"
          echo "Cluster : ${{ steps.tf.outputs.cluster_name }}"
          echo "Service : ${{ steps.tf.outputs.service_name }}"
          echo "Repository : ${{ steps.tf.outputs.repository_url }}"
          echo "Image Tag : ${IMAGE_TAG}"